### ISSUE TITLE
MMOC and function definitions in models

### ISSUE THREAD

**Issue by achimfritz97** [CIFASIS/qss-solver#154]
Hi,
I am having troubles to compile any model, that includes a function. For example the model airconds_cont.mo produces following error:

Line: 48 Class: getSection
ERROR: (10B00)
Abstract Syntax Tree: Class definition.
Initial section inside function definition.
File: "MY_PATH"/qss-solver-qss-solver-dev/models/parallel/airconds_cont/airconds_cont.mo
Line: 48 Class: getSection
ERROR: (10B00)
Abstract Syntax Tree: Class definition.
Initial section inside function definition.
Exit code: 1
Can't generate C file.

Same error goes for any model including a function definition, while other models seem to work great.

For my setup: I am using Ubuntu 20.04.4 LTS, GCC Compiler 9.4.0
Using the qss-solver-dev branch, as it is the default branch.

Any ideas on how I can fix the problem, or any hints of where to look in the code?
Thanks in advance for any help

**Comment by joaquinffernandez** [comment]
Hi @achimfritz97 thanks for reporting this issue, I was able to reproduce it, I will work on a fix for this and let you know when it's done.

**Comment by joaquinffernandez** [comment]
Done in 1f3d88fa9d59a462b11076a5d51a2fd20461b084
